import { PrismaClient, CollegeType } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';
import dotenv from 'dotenv';

dotenv.config();

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error('DATABASE_URL environment variable is required to run the seed script.');
}

const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

interface CollegeSeed {
  name: string;
  slug: string;
  location: string;
  state: string;
  type: CollegeType;
  description: string;
  overview: string;
  fees: number;
  rating: number;
  acceptanceRate: number;
  avgAid: number;
  gpa: number;
  sat: number;
  matchScore: number;
  research: number;
  campus: number;
  social: number;
  financial: number;
  innovation: number;
  diversity: number;
  courses: any;
  placements: any;
  majors: string[];
  tags: string[];
  imageUrl: string;
}

const colleges: CollegeSeed[] = [
  {
    name: 'Massachusetts Institute of Technology',
    slug: 'mit',
    location: 'Cambridge, MA',
    state: 'Massachusetts',
    type: 'REACH',
    description: 'World-leading research university renowned for science, engineering, and technology.',
    overview: 'MIT is a private research university founded in 1861. Known for its rigorous academics and groundbreaking research, MIT consistently ranks among the top universities worldwide. The campus spans 168 acres along the Charles River with iconic brutalist and modernist architecture.',
    fees: 57986,
    rating: 4.9,
    acceptanceRate: 3.96,
    avgAid: 53000,
    gpa: 3.96,
    sat: 1545,
    matchScore: 95,
    research: 98,
    campus: 85,
    social: 75,
    financial: 90,
    innovation: 99,
    diversity: 88,
    courses: [
      { name: 'Computer Science & Engineering', fee: 57986, duration: '4 years' },
      { name: 'Electrical Engineering', fee: 57986, duration: '4 years' },
      { name: 'Mechanical Engineering', fee: 57986, duration: '4 years' },
      { name: 'Physics', fee: 57986, duration: '4 years' },
      { name: 'Mathematics', fee: 57986, duration: '4 years' },
      { name: 'Biology', fee: 57986, duration: '4 years' },
    ],
    placements: { avgSalary: 108000, placementRate: 95, topRecruiters: ['Google', 'Apple', 'Microsoft', 'SpaceX', 'Goldman Sachs'] },
    majors: ['Computer Science', 'Engineering', 'Physics', 'Mathematics', 'Biology', 'AI/ML', 'Robotics'],
    tags: ['STEM', 'Ivy-Adjacent', 'Research', 'Innovation'],
    imageUrl: '/colleges/mit.jpg',
  },
  {
    name: 'Stanford University',
    slug: 'stanford',
    location: 'Stanford, CA',
    state: 'California',
    type: 'REACH',
    description: 'Silicon Valley powerhouse known for entrepreneurship and innovation.',
    overview: 'Stanford University is a private research university known for its entrepreneurial spirit and proximity to Silicon Valley. Founded in 1885, Stanford offers a uniquely collaborative academic environment across its 8,180-acre campus, making it one of the largest in the US.',
    fees: 56169,
    rating: 4.9,
    acceptanceRate: 3.68,
    avgAid: 56000,
    gpa: 3.95,
    sat: 1540,
    matchScore: 94,
    research: 97,
    campus: 95,
    social: 88,
    financial: 92,
    innovation: 98,
    diversity: 85,
    courses: [
      { name: 'Computer Science', fee: 56169, duration: '4 years' },
      { name: 'Engineering', fee: 56169, duration: '4 years' },
      { name: 'Business', fee: 56169, duration: '4 years' },
      { name: 'Human Biology', fee: 56169, duration: '4 years' },
      { name: 'Economics', fee: 56169, duration: '4 years' },
    ],
    placements: { avgSalary: 105000, placementRate: 94, topRecruiters: ['Google', 'Meta', 'Apple', 'Tesla', 'McKinsey'] },
    majors: ['Computer Science', 'Engineering', 'Business', 'Biology', 'Economics', 'AI/ML'],
    tags: ['STEM', 'Entrepreneurship', 'Research', 'Innovation'],
    imageUrl: '/colleges/stanford.jpg',
  },
  {
    name: 'Harvard University',
    slug: 'harvard',
    location: 'Cambridge, MA',
    state: 'Massachusetts',
    type: 'REACH',
    description: 'The oldest and most prestigious university in the United States.',
    overview: 'Harvard University, established in 1636, is the oldest institution of higher education in the US. Its rigorous academic programs, world-class faculty, and extensive alumni network make it a pinnacle of academic excellence. Harvard\'s endowment exceeds $50 billion, the largest of any academic institution.',
    fees: 55587,
    rating: 4.9,
    acceptanceRate: 3.19,
    avgAid: 55000,
    gpa: 3.94,
    sat: 1535,
    matchScore: 93,
    research: 96,
    campus: 90,
    social: 85,
    financial: 95,
    innovation: 90,
    diversity: 87,
    courses: [
      { name: 'Economics', fee: 55587, duration: '4 years' },
      { name: 'Computer Science', fee: 55587, duration: '4 years' },
      { name: 'Government', fee: 55587, duration: '4 years' },
      { name: 'Biology', fee: 55587, duration: '4 years' },
      { name: 'English', fee: 55587, duration: '4 years' },
    ],
    placements: { avgSalary: 98000, placementRate: 93, topRecruiters: ['Goldman Sachs', 'McKinsey', 'Google', 'BCG', 'JP Morgan'] },
    majors: ['Economics', 'Computer Science', 'Government', 'Biology', 'English', 'Law'],
    tags: ['Ivy League', 'Research', 'Liberal Arts', 'Prestige'],
    imageUrl: '/colleges/harvard.jpg',
  },
  {
    name: 'California Institute of Technology',
    slug: 'caltech',
    location: 'Pasadena, CA',
    state: 'California',
    type: 'REACH',
    description: 'Elite STEM research institute with the highest per-capita research spending.',
    overview: 'Caltech is a private research university with just ~980 undergrads. Despite its small size, it manages NASA\'s JPL and is a leader in physics, engineering, and planetary science. Caltech boasts the highest per-capita Nobel Prize count of any university.',
    fees: 58680,
    rating: 4.8,
    acceptanceRate: 3.6,
    avgAid: 48000,
    gpa: 3.97,
    sat: 1555,
    matchScore: 92,
    research: 99,
    campus: 70,
    social: 60,
    financial: 85,
    innovation: 97,
    diversity: 72,
    courses: [
      { name: 'Physics', fee: 58680, duration: '4 years' },
      { name: 'Computer Science', fee: 58680, duration: '4 years' },
      { name: 'Chemical Engineering', fee: 58680, duration: '4 years' },
      { name: 'Biology', fee: 58680, duration: '4 years' },
    ],
    placements: { avgSalary: 102000, placementRate: 92, topRecruiters: ['SpaceX', 'Google', 'NASA/JPL', 'Apple', 'Boeing'] },
    majors: ['Physics', 'Computer Science', 'Engineering', 'Biology', 'Chemistry', 'Astrophysics'],
    tags: ['STEM', 'Research', 'Small Class Size'],
    imageUrl: '/colleges/caltech.jpg',
  },
  {
    name: 'Carnegie Mellon University',
    slug: 'cmu',
    location: 'Pittsburgh, PA',
    state: 'Pennsylvania',
    type: 'REACH',
    description: 'Top-ranked for CS, robotics, and AI with strong arts programs.',
    overview: 'Carnegie Mellon University is renowned for its programs in computer science, robotics, and artificial intelligence. The School of Computer Science is consistently ranked #1 globally. CMU also excels in fine arts, business, and public policy.',
    fees: 58924,
    rating: 4.7,
    acceptanceRate: 11.5,
    avgAid: 42000,
    gpa: 3.88,
    sat: 1520,
    matchScore: 90,
    research: 95,
    campus: 78,
    social: 72,
    financial: 75,
    innovation: 96,
    diversity: 82,
    courses: [
      { name: 'Computer Science', fee: 58924, duration: '4 years' },
      { name: 'Robotics', fee: 58924, duration: '4 years' },
      { name: 'AI & Machine Learning', fee: 58924, duration: '4 years' },
      { name: 'Business Administration', fee: 58924, duration: '4 years' },
      { name: 'Information Systems', fee: 58924, duration: '4 years' },
    ],
    placements: { avgSalary: 105000, placementRate: 93, topRecruiters: ['Google', 'Amazon', 'Meta', 'Microsoft', 'Apple'] },
    majors: ['Computer Science', 'Robotics', 'AI/ML', 'Business', 'Design', 'Engineering'],
    tags: ['STEM', 'CS', 'AI', 'Research'],
    imageUrl: '/colleges/cmu.jpg',
  },
  {
    name: 'University of California, Berkeley',
    slug: 'uc-berkeley',
    location: 'Berkeley, CA',
    state: 'California',
    type: 'TARGET',
    description: 'Top public university with strong EECS and business programs.',
    overview: 'UC Berkeley is the flagship campus of the University of California system. Known for its top-ranked EECS, business, and chemistry programs, Berkeley combines research excellence with public university accessibility. The campus overlooks the San Francisco Bay.',
    fees: 44066,
    rating: 4.7,
    acceptanceRate: 11.6,
    avgAid: 22000,
    gpa: 3.89,
    sat: 1440,
    matchScore: 88,
    research: 94,
    campus: 82,
    social: 85,
    financial: 65,
    innovation: 92,
    diversity: 90,
    courses: [
      { name: 'EECS', fee: 44066, duration: '4 years' },
      { name: 'Business Administration', fee: 44066, duration: '4 years' },
      { name: 'Data Science', fee: 44066, duration: '4 years' },
      { name: 'Chemistry', fee: 44066, duration: '4 years' },
    ],
    placements: { avgSalary: 95000, placementRate: 90, topRecruiters: ['Google', 'Apple', 'Meta', 'Amazon', 'Deloitte'] },
    majors: ['Computer Science', 'EECS', 'Business', 'Data Science', 'Chemistry'],
    tags: ['STEM', 'Public', 'Research', 'Innovation'],
    imageUrl: '/colleges/berkeley.jpg',
  },
  {
    name: 'Georgia Institute of Technology',
    slug: 'georgia-tech',
    location: 'Atlanta, GA',
    state: 'Georgia',
    type: 'TARGET',
    description: 'Premier public tech university with outstanding engineering and CS.',
    overview: 'Georgia Tech is one of the nation\'s top public research universities, excelling in engineering, computing, sciences, business, and design. Located in Atlanta\'s tech corridor, GT offers exceptional value with strong industry connections.',
    fees: 33794,
    rating: 4.6,
    acceptanceRate: 17.0,
    avgAid: 15000,
    gpa: 3.82,
    sat: 1440,
    matchScore: 85,
    research: 90,
    campus: 80,
    social: 78,
    financial: 80,
    innovation: 91,
    diversity: 75,
    courses: [
      { name: 'Computer Science', fee: 33794, duration: '4 years' },
      { name: 'Mechanical Engineering', fee: 33794, duration: '4 years' },
      { name: 'Industrial Engineering', fee: 33794, duration: '4 years' },
      { name: 'Biomedical Engineering', fee: 33794, duration: '4 years' },
    ],
    placements: { avgSalary: 85000, placementRate: 91, topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Lockheed Martin', 'Delta'] },
    majors: ['Computer Science', 'Engineering', 'Business', 'Design', 'Biology'],
    tags: ['STEM', 'Public', 'Engineering', 'Value'],
    imageUrl: '/colleges/gatech.jpg',
  },
  {
    name: 'Cornell University',
    slug: 'cornell',
    location: 'Ithaca, NY',
    state: 'New York',
    type: 'REACH',
    description: 'Ivy League university with unique mix of public and private colleges.',
    overview: 'Cornell is the largest Ivy League university with seven undergraduate colleges. Known for its beautiful Finger Lakes campus, diverse academic offerings from hotel administration to engineering, and commitment to public engagement as a land-grant institution.',
    fees: 62456,
    rating: 4.7,
    acceptanceRate: 7.3,
    avgAid: 50000,
    gpa: 3.90,
    sat: 1510,
    matchScore: 89,
    research: 92,
    campus: 92,
    social: 80,
    financial: 82,
    innovation: 88,
    diversity: 83,
    courses: [
      { name: 'Computer Science', fee: 62456, duration: '4 years' },
      { name: 'Engineering', fee: 62456, duration: '4 years' },
      { name: 'Hotel Administration', fee: 62456, duration: '4 years' },
      { name: 'Agriculture', fee: 62456, duration: '4 years' },
      { name: 'Architecture', fee: 62456, duration: '4 years' },
    ],
    placements: { avgSalary: 88000, placementRate: 90, topRecruiters: ['Google', 'Goldman Sachs', 'JP Morgan', 'Deloitte', 'McKinsey'] },
    majors: ['Computer Science', 'Engineering', 'Hotel Admin', 'Agriculture', 'Architecture', 'Biology'],
    tags: ['Ivy League', 'Research', 'Engineering'],
    imageUrl: '/colleges/cornell.jpg',
  },
  {
    name: 'Princeton University',
    slug: 'princeton',
    location: 'Princeton, NJ',
    state: 'New Jersey',
    type: 'REACH',
    description: 'Ivy League gem with unmatched undergraduate teaching and generous aid.',
    overview: 'Princeton University, founded in 1746, is known for its focus on undergraduate education and generous financial aid program. With a student-to-faculty ratio of 5:1, Princeton offers an intimate academic experience at one of the most beautiful collegiate campuses in America.',
    fees: 57410,
    rating: 4.9,
    acceptanceRate: 3.73,
    avgAid: 59000,
    gpa: 3.93,
    sat: 1540,
    matchScore: 93,
    research: 95,
    campus: 96,
    social: 82,
    financial: 97,
    innovation: 89,
    diversity: 80,
    courses: [
      { name: 'Computer Science', fee: 57410, duration: '4 years' },
      { name: 'Economics', fee: 57410, duration: '4 years' },
      { name: 'Public Policy', fee: 57410, duration: '4 years' },
      { name: 'Engineering', fee: 57410, duration: '4 years' },
      { name: 'Mathematics', fee: 57410, duration: '4 years' },
    ],
    placements: { avgSalary: 95000, placementRate: 92, topRecruiters: ['Google', 'Goldman Sachs', 'McKinsey', 'Jane Street', 'Citadel'] },
    majors: ['Computer Science', 'Economics', 'Public Policy', 'Engineering', 'Mathematics', 'Physics'],
    tags: ['Ivy League', 'Liberal Arts', 'Generous Aid', 'Research'],
    imageUrl: '/colleges/princeton.jpg',
  },
  {
    name: 'University of California, Los Angeles',
    slug: 'ucla',
    location: 'Los Angeles, CA',
    state: 'California',
    type: 'TARGET',
    description: 'Prestigious public university with vibrant campus life in LA.',
    overview: 'UCLA is one of the most applied-to universities in the US. Located in Westwood, Los Angeles, it combines academic excellence with a vibrant campus culture, strong athletics, and proximity to entertainment and tech industries.',
    fees: 43022,
    rating: 4.6,
    acceptanceRate: 8.6,
    avgAid: 21000,
    gpa: 3.90,
    sat: 1420,
    matchScore: 86,
    research: 90,
    campus: 92,
    social: 95,
    financial: 60,
    innovation: 85,
    diversity: 92,
    courses: [
      { name: 'Computer Science', fee: 43022, duration: '4 years' },
      { name: 'Biology', fee: 43022, duration: '4 years' },
      { name: 'Psychology', fee: 43022, duration: '4 years' },
      { name: 'Economics', fee: 43022, duration: '4 years' },
      { name: 'Film & Television', fee: 43022, duration: '4 years' },
    ],
    placements: { avgSalary: 78000, placementRate: 88, topRecruiters: ['Google', 'Disney', 'Amazon', 'Netflix', 'Deloitte'] },
    majors: ['Computer Science', 'Biology', 'Psychology', 'Film', 'Economics', 'Pre-Med'],
    tags: ['Public', 'Research', 'Campus Life', 'Arts'],
    imageUrl: '/colleges/ucla.jpg',
  },
  {
    name: 'University of Texas at Austin',
    slug: 'ut-austin',
    location: 'Austin, TX',
    state: 'Texas',
    type: 'TARGET',
    description: 'Flagship Texas public university with top CS and engineering programs.',
    overview: 'UT Austin is a leading public research university located in the vibrant tech hub of Austin. With strong programs in CS, engineering, and business, it offers exceptional value and has a massive alumni network across technology and energy sectors.',
    fees: 40032,
    rating: 4.5,
    acceptanceRate: 29.0,
    avgAid: 14000,
    gpa: 3.75,
    sat: 1380,
    matchScore: 80,
    research: 88,
    campus: 85,
    social: 90,
    financial: 75,
    innovation: 86,
    diversity: 78,
    courses: [
      { name: 'Computer Science', fee: 40032, duration: '4 years' },
      { name: 'Engineering', fee: 40032, duration: '4 years' },
      { name: 'Business', fee: 40032, duration: '4 years' },
      { name: 'Communication', fee: 40032, duration: '4 years' },
    ],
    placements: { avgSalary: 78000, placementRate: 87, topRecruiters: ['Google', 'Dell', 'Amazon', 'Facebook', 'ExxonMobil'] },
    majors: ['Computer Science', 'Engineering', 'Business', 'Communication', 'Biology'],
    tags: ['Public', 'STEM', 'Value', 'Big Campus'],
    imageUrl: '/colleges/utaustin.jpg',
  },
  {
    name: 'Purdue University',
    slug: 'purdue',
    location: 'West Lafayette, IN',
    state: 'Indiana',
    type: 'SAFETY',
    description: 'Strong engineering and CS programs with excellent value.',
    overview: 'Purdue University is a premier public research institution known for engineering, CS, and aeronautics. Famous as the "Cradle of Astronauts," Purdue has produced 27 astronauts including Neil Armstrong. The university has frozen tuition for over a decade.',
    fees: 28794,
    rating: 4.4,
    acceptanceRate: 53.0,
    avgAid: 12000,
    gpa: 3.65,
    sat: 1330,
    matchScore: 76,
    research: 85,
    campus: 78,
    social: 80,
    financial: 88,
    innovation: 82,
    diversity: 70,
    courses: [
      { name: 'Computer Science', fee: 28794, duration: '4 years' },
      { name: 'Mechanical Engineering', fee: 28794, duration: '4 years' },
      { name: 'Aerospace Engineering', fee: 28794, duration: '4 years' },
      { name: 'Pharmacy', fee: 28794, duration: '4 years' },
    ],
    placements: { avgSalary: 72000, placementRate: 88, topRecruiters: ['Amazon', 'Google', 'Microsoft', 'Caterpillar', 'Rolls Royce'] },
    majors: ['Computer Science', 'Engineering', 'Aerospace', 'Pharmacy', 'Agriculture'],
    tags: ['STEM', 'Public', 'Value', 'Engineering'],
    imageUrl: '/colleges/purdue.jpg',
  },
  {
    name: 'University of Michigan',
    slug: 'umich',
    location: 'Ann Arbor, MI',
    state: 'Michigan',
    type: 'TARGET',
    description: 'Top public university with strong engineering and business programs.',
    overview: 'The University of Michigan is among the most prestigious public universities in the US, with top-ranked programs in engineering, business, medicine, and law. Ann Arbor is consistently rated one of the best college towns in America.',
    fees: 52266,
    rating: 4.6,
    acceptanceRate: 17.7,
    avgAid: 20000,
    gpa: 3.88,
    sat: 1460,
    matchScore: 84,
    research: 93,
    campus: 90,
    social: 92,
    financial: 65,
    innovation: 88,
    diversity: 78,
    courses: [
      { name: 'Computer Science', fee: 52266, duration: '4 years' },
      { name: 'Engineering', fee: 52266, duration: '4 years' },
      { name: 'Ross Business', fee: 52266, duration: '4 years' },
      { name: 'Pre-Med', fee: 52266, duration: '4 years' },
    ],
    placements: { avgSalary: 82000, placementRate: 90, topRecruiters: ['Google', 'Ford', 'Amazon', 'McKinsey', 'JP Morgan'] },
    majors: ['Computer Science', 'Engineering', 'Business', 'Pre-Med', 'Psychology'],
    tags: ['Public', 'Research', 'Big Ten', 'Campus Life'],
    imageUrl: '/colleges/umich.jpg',
  },
  {
    name: 'University of Illinois Urbana-Champaign',
    slug: 'uiuc',
    location: 'Champaign, IL',
    state: 'Illinois',
    type: 'TARGET',
    description: 'Top-5 CS program and strong engineering at great value.',
    overview: 'UIUC\'s Grainger College of Engineering is among the best in the nation, and the CS department is consistently ranked top 5. UIUC is a leading research institution with a beautiful Midwest campus and excellent career placement.',
    fees: 34312,
    rating: 4.5,
    acceptanceRate: 43.7,
    avgAid: 16000,
    gpa: 3.72,
    sat: 1410,
    matchScore: 82,
    research: 91,
    campus: 80,
    social: 82,
    financial: 78,
    innovation: 90,
    diversity: 72,
    courses: [
      { name: 'Computer Science', fee: 34312, duration: '4 years' },
      { name: 'Electrical Engineering', fee: 34312, duration: '4 years' },
      { name: 'Business', fee: 34312, duration: '4 years' },
      { name: 'Accounting', fee: 34312, duration: '4 years' },
    ],
    placements: { avgSalary: 85000, placementRate: 90, topRecruiters: ['Google', 'Amazon', 'Microsoft', 'Meta', 'Qualcomm'] },
    majors: ['Computer Science', 'Engineering', 'Business', 'Accounting', 'Physics'],
    tags: ['STEM', 'Public', 'CS', 'Value'],
    imageUrl: '/colleges/uiuc.jpg',
  },
  {
    name: 'University of Washington',
    slug: 'uw-seattle',
    location: 'Seattle, WA',
    state: 'Washington',
    type: 'TARGET',
    description: 'Pacific Northwest powerhouse in CS, medicine, and research.',
    overview: 'The University of Washington is a public research university in Seattle with one of the strongest CS programs in the world. Its proximity to Amazon, Microsoft, and Boeing provides outstanding industry connections and internship pipelines.',
    fees: 39906,
    rating: 4.5,
    acceptanceRate: 43.0,
    avgAid: 18000,
    gpa: 3.78,
    sat: 1390,
    matchScore: 81,
    research: 92,
    campus: 88,
    social: 80,
    financial: 70,
    innovation: 89,
    diversity: 82,
    courses: [
      { name: 'Computer Science', fee: 39906, duration: '4 years' },
      { name: 'Information Science', fee: 39906, duration: '4 years' },
      { name: 'Engineering', fee: 39906, duration: '4 years' },
      { name: 'Pre-Med', fee: 39906, duration: '4 years' },
    ],
    placements: { avgSalary: 90000, placementRate: 89, topRecruiters: ['Amazon', 'Microsoft', 'Boeing', 'Google', 'Meta'] },
    majors: ['Computer Science', 'Information Science', 'Engineering', 'Biology', 'Pre-Med'],
    tags: ['STEM', 'Public', 'Tech Hub', 'Research'],
    imageUrl: '/colleges/uw.jpg',
  },
  {
    name: 'New York University',
    slug: 'nyu',
    location: 'New York, NY',
    state: 'New York',
    type: 'TARGET',
    description: 'Urban university with global campus network and strong business/arts.',
    overview: 'NYU is a private research university with campuses in New York City, Abu Dhabi, and Shanghai. Known for Stern Business, Tisch Arts, and Tandon Engineering, NYU offers an unmatched urban education experience in the heart of Manhattan.',
    fees: 58168,
    rating: 4.5,
    acceptanceRate: 12.2,
    avgAid: 38000,
    gpa: 3.70,
    sat: 1470,
    matchScore: 83,
    research: 85,
    campus: 70,
    social: 95,
    financial: 55,
    innovation: 84,
    diversity: 95,
    courses: [
      { name: 'Computer Science', fee: 58168, duration: '4 years' },
      { name: 'Business (Stern)', fee: 58168, duration: '4 years' },
      { name: 'Film & TV (Tisch)', fee: 58168, duration: '4 years' },
      { name: 'Data Science', fee: 58168, duration: '4 years' },
    ],
    placements: { avgSalary: 82000, placementRate: 87, topRecruiters: ['Goldman Sachs', 'JP Morgan', 'Google', 'Deloitte', 'NBC'] },
    majors: ['Computer Science', 'Business', 'Film', 'Data Science', 'Economics', 'Art'],
    tags: ['Urban', 'Business', 'Arts', 'Global'],
    imageUrl: '/colleges/nyu.jpg',
  },
  {
    name: 'Columbia University',
    slug: 'columbia',
    location: 'New York, NY',
    state: 'New York',
    type: 'REACH',
    description: 'Ivy League university in the heart of New York City.',
    overview: 'Columbia University, founded in 1754, is an Ivy League university located in Manhattan\'s Morningside Heights. Known for its Core Curriculum, Columbia offers a rigorous liberal arts education alongside world-class professional schools in law, business, and journalism.',
    fees: 63530,
    rating: 4.7,
    acceptanceRate: 3.9,
    avgAid: 56000,
    gpa: 3.92,
    sat: 1530,
    matchScore: 91,
    research: 94,
    campus: 75,
    social: 88,
    financial: 88,
    innovation: 87,
    diversity: 90,
    courses: [
      { name: 'Computer Science', fee: 63530, duration: '4 years' },
      { name: 'Economics', fee: 63530, duration: '4 years' },
      { name: 'Political Science', fee: 63530, duration: '4 years' },
      { name: 'Engineering', fee: 63530, duration: '4 years' },
    ],
    placements: { avgSalary: 90000, placementRate: 91, topRecruiters: ['Goldman Sachs', 'McKinsey', 'Google', 'JP Morgan', 'Morgan Stanley'] },
    majors: ['Computer Science', 'Economics', 'Political Science', 'Engineering', 'English'],
    tags: ['Ivy League', 'Urban', 'Research', 'Liberal Arts'],
    imageUrl: '/colleges/columbia.jpg',
  },
  {
    name: 'Yale University',
    slug: 'yale',
    location: 'New Haven, CT',
    state: 'Connecticut',
    type: 'REACH',
    description: 'Ivy League leader in arts, humanities, and law.',
    overview: 'Yale University is a private Ivy League research university founded in 1701. Known for its exceptional programs in law, drama, and art, Yale offers a residential college system that fosters tight-knit community and intellectual engagement.',
    fees: 62250,
    rating: 4.8,
    acceptanceRate: 4.35,
    avgAid: 57000,
    gpa: 3.93,
    sat: 1530,
    matchScore: 92,
    research: 93,
    campus: 93,
    social: 85,
    financial: 93,
    innovation: 85,
    diversity: 82,
    courses: [
      { name: 'Economics', fee: 62250, duration: '4 years' },
      { name: 'Political Science', fee: 62250, duration: '4 years' },
      { name: 'History', fee: 62250, duration: '4 years' },
      { name: 'Computer Science', fee: 62250, duration: '4 years' },
      { name: 'English', fee: 62250, duration: '4 years' },
    ],
    placements: { avgSalary: 88000, placementRate: 90, topRecruiters: ['McKinsey', 'Goldman Sachs', 'Google', 'BCG', 'Teach For America'] },
    majors: ['Economics', 'Political Science', 'History', 'Computer Science', 'English', 'Law'],
    tags: ['Ivy League', 'Liberal Arts', 'Law', 'Arts'],
    imageUrl: '/colleges/yale.jpg',
  },
  {
    name: 'University of Pennsylvania',
    slug: 'upenn',
    location: 'Philadelphia, PA',
    state: 'Pennsylvania',
    type: 'REACH',
    description: 'Ivy League with the top business school (Wharton) in the world.',
    overview: 'UPenn is home to the Wharton School, the world\'s premier business school. Founded by Benjamin Franklin, Penn integrates business, engineering, nursing, and liberal arts in a uniquely interdisciplinary environment in Philadelphia.',
    fees: 61710,
    rating: 4.7,
    acceptanceRate: 5.9,
    avgAid: 54000,
    gpa: 3.91,
    sat: 1520,
    matchScore: 90,
    research: 92,
    campus: 85,
    social: 88,
    financial: 85,
    innovation: 90,
    diversity: 83,
    courses: [
      { name: 'Business (Wharton)', fee: 61710, duration: '4 years' },
      { name: 'Engineering', fee: 61710, duration: '4 years' },
      { name: 'Computer Science', fee: 61710, duration: '4 years' },
      { name: 'Nursing', fee: 61710, duration: '4 years' },
    ],
    placements: { avgSalary: 95000, placementRate: 92, topRecruiters: ['Goldman Sachs', 'McKinsey', 'Google', 'JP Morgan', 'BCG'] },
    majors: ['Business', 'Engineering', 'Computer Science', 'Nursing', 'Economics'],
    tags: ['Ivy League', 'Business', 'Wharton', 'Research'],
    imageUrl: '/colleges/upenn.jpg',
  },
  {
    name: 'Duke University',
    slug: 'duke',
    location: 'Durham, NC',
    state: 'North Carolina',
    type: 'REACH',
    description: 'Elite private university with top programs in medicine and public policy.',
    overview: 'Duke University combines rigorous academics with vibrant campus life. Known for its medical center, Fuqua School of Business, and powerhouse basketball program, Duke sits on 8,600 acres of stunning Gothic campus and Duke Forest.',
    fees: 60489,
    rating: 4.7,
    acceptanceRate: 5.0,
    avgAid: 52000,
    gpa: 3.92,
    sat: 1520,
    matchScore: 89,
    research: 93,
    campus: 94,
    social: 90,
    financial: 84,
    innovation: 88,
    diversity: 80,
    courses: [
      { name: 'Computer Science', fee: 60489, duration: '4 years' },
      { name: 'Public Policy', fee: 60489, duration: '4 years' },
      { name: 'Biology', fee: 60489, duration: '4 years' },
      { name: 'Economics', fee: 60489, duration: '4 years' },
    ],
    placements: { avgSalary: 85000, placementRate: 91, topRecruiters: ['McKinsey', 'Goldman Sachs', 'Google', 'Deloitte', 'Duke Health'] },
    majors: ['Computer Science', 'Public Policy', 'Biology', 'Economics', 'Pre-Med'],
    tags: ['Research', 'Pre-Med', 'Athletics', 'Prestige'],
    imageUrl: '/colleges/duke.jpg',
  },
  {
    name: 'Northwestern University',
    slug: 'northwestern',
    location: 'Evanston, IL',
    state: 'Illinois',
    type: 'REACH',
    description: 'Elite private university on Lake Michigan with top journalism and engineering.',
    overview: 'Northwestern University combines a strong liberal arts foundation with professional programs in journalism (Medill), engineering (McCormick), and performing arts. Its lakefront campus north of Chicago offers stunning views and Big Ten athletics.',
    fees: 60768,
    rating: 4.6,
    acceptanceRate: 7.0,
    avgAid: 48000,
    gpa: 3.90,
    sat: 1510,
    matchScore: 87,
    research: 91,
    campus: 90,
    social: 85,
    financial: 80,
    innovation: 86,
    diversity: 78,
    courses: [
      { name: 'Journalism (Medill)', fee: 60768, duration: '4 years' },
      { name: 'Engineering', fee: 60768, duration: '4 years' },
      { name: 'Economics', fee: 60768, duration: '4 years' },
      { name: 'Computer Science', fee: 60768, duration: '4 years' },
    ],
    placements: { avgSalary: 82000, placementRate: 89, topRecruiters: ['Google', 'McKinsey', 'NBC', 'Goldman Sachs', 'Microsoft'] },
    majors: ['Journalism', 'Engineering', 'Economics', 'Computer Science', 'Theatre'],
    tags: ['Research', 'Journalism', 'Big Ten', 'Liberal Arts'],
    imageUrl: '/colleges/northwestern.jpg',
  },
  {
    name: 'Brown University',
    slug: 'brown',
    location: 'Providence, RI',
    state: 'Rhode Island',
    type: 'REACH',
    description: 'Ivy League with unique open curriculum and creative academic freedom.',
    overview: 'Brown is known for its distinctive Open Curriculum, which allows students to design their own course of study without distribution requirements. This fosters intellectual curiosity and creative exploration in a supportive, collaborative environment.',
    fees: 62680,
    rating: 4.6,
    acceptanceRate: 5.0,
    avgAid: 52000,
    gpa: 3.91,
    sat: 1510,
    matchScore: 88,
    research: 88,
    campus: 88,
    social: 82,
    financial: 86,
    innovation: 85,
    diversity: 82,
    courses: [
      { name: 'Computer Science', fee: 62680, duration: '4 years' },
      { name: 'Applied Mathematics', fee: 62680, duration: '4 years' },
      { name: 'Economics', fee: 62680, duration: '4 years' },
      { name: 'Biology', fee: 62680, duration: '4 years' },
    ],
    placements: { avgSalary: 78000, placementRate: 88, topRecruiters: ['Google', 'Goldman Sachs', 'McKinsey', 'BCG', 'Epic Systems'] },
    majors: ['Computer Science', 'Applied Math', 'Economics', 'Biology', 'Cognitive Science'],
    tags: ['Ivy League', 'Open Curriculum', 'Liberal Arts', 'Creative'],
    imageUrl: '/colleges/brown.jpg',
  },
  {
    name: 'Rice University',
    slug: 'rice',
    location: 'Houston, TX',
    state: 'Texas',
    type: 'TARGET',
    description: 'Highly-ranked private university with exceptional value and residential college system.',
    overview: 'Rice University offers a top-tier education at significantly lower cost than peers. Its residential college system fosters community, and its location in Houston provides access to the energy, medical, and space industries.',
    fees: 54100,
    rating: 4.6,
    acceptanceRate: 7.7,
    avgAid: 46000,
    gpa: 3.88,
    sat: 1520,
    matchScore: 87,
    research: 89,
    campus: 88,
    social: 85,
    financial: 90,
    innovation: 87,
    diversity: 78,
    courses: [
      { name: 'Computer Science', fee: 54100, duration: '4 years' },
      { name: 'Engineering', fee: 54100, duration: '4 years' },
      { name: 'Architecture', fee: 54100, duration: '4 years' },
      { name: 'Business', fee: 54100, duration: '4 years' },
    ],
    placements: { avgSalary: 80000, placementRate: 89, topRecruiters: ['ExxonMobil', 'Google', 'Shell', 'NASA', 'Deloitte'] },
    majors: ['Computer Science', 'Engineering', 'Architecture', 'Business', 'Biology'],
    tags: ['STEM', 'Value', 'Research', 'Residential'],
    imageUrl: '/colleges/rice.jpg',
  },
  {
    name: 'Vanderbilt University',
    slug: 'vanderbilt',
    location: 'Nashville, TN',
    state: 'Tennessee',
    type: 'TARGET',
    description: 'Top private university in the South with strong medicine and education programs.',
    overview: 'Vanderbilt is a private research university in Nashville known for its beautiful campus, strong pre-med pipeline, and vibrant student life. The university is consistently ranked among the top 15 national universities.',
    fees: 58130,
    rating: 4.5,
    acceptanceRate: 5.6,
    avgAid: 50000,
    gpa: 3.87,
    sat: 1510,
    matchScore: 85,
    research: 88,
    campus: 92,
    social: 90,
    financial: 82,
    innovation: 80,
    diversity: 75,
    courses: [
      { name: 'Engineering', fee: 58130, duration: '4 years' },
      { name: 'Education', fee: 58130, duration: '4 years' },
      { name: 'Economics', fee: 58130, duration: '4 years' },
      { name: 'Computer Science', fee: 58130, duration: '4 years' },
    ],
    placements: { avgSalary: 75000, placementRate: 87, topRecruiters: ['Deloitte', 'EY', 'Goldman Sachs', 'HCA Healthcare', 'Google'] },
    majors: ['Engineering', 'Education', 'Economics', 'Computer Science', 'Pre-Med'],
    tags: ['Research', 'Pre-Med', 'Southern', 'Campus Life'],
    imageUrl: '/colleges/vanderbilt.jpg',
  },
  {
    name: 'Washington University in St. Louis',
    slug: 'washu',
    location: 'St. Louis, MO',
    state: 'Missouri',
    type: 'TARGET',
    description: 'Leading research university with top medical and business schools.',
    overview: 'WashU is a highly selective private university known for its medical school, Olin Business School, and collaborative academic culture. The campus is one of the most beautiful in the country with stunning collegiate Gothic architecture.',
    fees: 59420,
    rating: 4.5,
    acceptanceRate: 11.0,
    avgAid: 49000,
    gpa: 3.86,
    sat: 1510,
    matchScore: 84,
    research: 90,
    campus: 93,
    social: 82,
    financial: 83,
    innovation: 82,
    diversity: 76,
    courses: [
      { name: 'Pre-Med', fee: 59420, duration: '4 years' },
      { name: 'Business', fee: 59420, duration: '4 years' },
      { name: 'Computer Science', fee: 59420, duration: '4 years' },
      { name: 'Political Science', fee: 59420, duration: '4 years' },
    ],
    placements: { avgSalary: 78000, placementRate: 88, topRecruiters: ['BJC Healthcare', 'Deloitte', 'Google', 'BCG', 'JP Morgan'] },
    majors: ['Pre-Med', 'Business', 'Computer Science', 'Political Science', 'Biology'],
    tags: ['Research', 'Pre-Med', 'Business', 'Beautiful Campus'],
    imageUrl: '/colleges/washu.jpg',
  },
  {
    name: 'Emory University',
    slug: 'emory',
    location: 'Atlanta, GA',
    state: 'Georgia',
    type: 'TARGET',
    description: 'Top private university with one of the nation\'s best medical programs.',
    overview: 'Emory University is a leading private research university in Atlanta known for its close ties to the CDC and strong programs in medicine, public health, and business. The Oxford campus offers a unique two-year liberal arts experience.',
    fees: 57948,
    rating: 4.4,
    acceptanceRate: 11.4,
    avgAid: 44000,
    gpa: 3.80,
    sat: 1460,
    matchScore: 80,
    research: 88,
    campus: 85,
    social: 78,
    financial: 78,
    innovation: 82,
    diversity: 80,
    courses: [
      { name: 'Biology', fee: 57948, duration: '4 years' },
      { name: 'Business', fee: 57948, duration: '4 years' },
      { name: 'Nursing', fee: 57948, duration: '4 years' },
      { name: 'Computer Science', fee: 57948, duration: '4 years' },
    ],
    placements: { avgSalary: 72000, placementRate: 86, topRecruiters: ['CDC', 'Deloitte', 'EY', 'Delta', 'Google'] },
    majors: ['Biology', 'Business', 'Nursing', 'Computer Science', 'Public Health'],
    tags: ['Research', 'Pre-Med', 'CDC', 'Southern'],
    imageUrl: '/colleges/emory.jpg',
  },
  {
    name: 'University of Southern California',
    slug: 'usc',
    location: 'Los Angeles, CA',
    state: 'California',
    type: 'TARGET',
    description: 'Leading private university in LA with top film and engineering programs.',
    overview: 'USC is a leading private research university in the heart of Los Angeles. Known for its film school (top in the world), strong engineering, and massive alumni network (the Trojan Family), USC offers unmatched industry connections.',
    fees: 62352,
    rating: 4.5,
    acceptanceRate: 9.9,
    avgAid: 40000,
    gpa: 3.80,
    sat: 1470,
    matchScore: 82,
    research: 86,
    campus: 82,
    social: 92,
    financial: 60,
    innovation: 85,
    diversity: 88,
    courses: [
      { name: 'Film & TV', fee: 62352, duration: '4 years' },
      { name: 'Computer Science', fee: 62352, duration: '4 years' },
      { name: 'Business', fee: 62352, duration: '4 years' },
      { name: 'Engineering', fee: 62352, duration: '4 years' },
    ],
    placements: { avgSalary: 80000, placementRate: 88, topRecruiters: ['Disney', 'Google', 'Amazon', 'Warner Bros', 'SpaceX'] },
    majors: ['Film', 'Computer Science', 'Business', 'Engineering', 'Communication'],
    tags: ['Film', 'STEM', 'Urban', 'Alumni Network'],
    imageUrl: '/colleges/usc.jpg',
  },
  {
    name: 'Johns Hopkins University',
    slug: 'jhu',
    location: 'Baltimore, MD',
    state: 'Maryland',
    type: 'REACH',
    description: 'World-leading research university and medical institution.',
    overview: 'Johns Hopkins pioneered the modern research university model in America. It leads the nation in federal R&D funding and is world-renowned for its medical school and Bloomberg School of Public Health. JHU also has strong programs in international studies and engineering.',
    fees: 59950,
    rating: 4.6,
    acceptanceRate: 6.5,
    avgAid: 50000,
    gpa: 3.90,
    sat: 1520,
    matchScore: 88,
    research: 97,
    campus: 78,
    social: 72,
    financial: 82,
    innovation: 90,
    diversity: 80,
    courses: [
      { name: 'Biomedical Engineering', fee: 59950, duration: '4 years' },
      { name: 'Public Health', fee: 59950, duration: '4 years' },
      { name: 'Computer Science', fee: 59950, duration: '4 years' },
      { name: 'International Studies', fee: 59950, duration: '4 years' },
    ],
    placements: { avgSalary: 82000, placementRate: 89, topRecruiters: ['Johns Hopkins Hospital', 'Google', 'NIH', 'McKinsey', 'Amazon'] },
    majors: ['Biomedical Engineering', 'Public Health', 'Computer Science', 'International Studies', 'Biology'],
    tags: ['Research', 'Pre-Med', 'Public Health', 'Engineering'],
    imageUrl: '/colleges/jhu.jpg',
  },
  {
    name: 'University of Notre Dame',
    slug: 'notre-dame',
    location: 'Notre Dame, IN',
    state: 'Indiana',
    type: 'TARGET',
    description: 'Prestigious Catholic university with exceptional alumni loyalty.',
    overview: 'Notre Dame is a prestigious private Catholic university known for its strong sense of community, exceptional undergraduate teaching, and legendary athletics program. The campus features the iconic Golden Dome and Touchdown Jesus.',
    fees: 58843,
    rating: 4.5,
    acceptanceRate: 12.9,
    avgAid: 46000,
    gpa: 3.82,
    sat: 1480,
    matchScore: 82,
    research: 82,
    campus: 95,
    social: 92,
    financial: 78,
    innovation: 78,
    diversity: 68,
    courses: [
      { name: 'Business', fee: 58843, duration: '4 years' },
      { name: 'Engineering', fee: 58843, duration: '4 years' },
      { name: 'Political Science', fee: 58843, duration: '4 years' },
      { name: 'Computer Science', fee: 58843, duration: '4 years' },
    ],
    placements: { avgSalary: 76000, placementRate: 88, topRecruiters: ['Deloitte', 'EY', 'Goldman Sachs', 'Google', 'PwC'] },
    majors: ['Business', 'Engineering', 'Political Science', 'Computer Science', 'Theology'],
    tags: ['Catholic', 'Athletics', 'Community', 'Business'],
    imageUrl: '/colleges/notredame.jpg',
  },
  {
    name: 'University of Virginia',
    slug: 'uva',
    location: 'Charlottesville, VA',
    state: 'Virginia',
    type: 'TARGET',
    description: 'Thomas Jefferson\'s university with outstanding public education.',
    overview: 'Founded by Thomas Jefferson, UVA is a flagship public university known for its historic Grounds, Honor Code, and strong programs in business (McIntire), law, and medicine. The Lawn is a UNESCO World Heritage Site.',
    fees: 53666,
    rating: 4.5,
    acceptanceRate: 16.3,
    avgAid: 20000,
    gpa: 3.82,
    sat: 1430,
    matchScore: 80,
    research: 85,
    campus: 94,
    social: 88,
    financial: 72,
    innovation: 78,
    diversity: 72,
    courses: [
      { name: 'Business (McIntire)', fee: 53666, duration: '4 years' },
      { name: 'Computer Science', fee: 53666, duration: '4 years' },
      { name: 'Economics', fee: 53666, duration: '4 years' },
      { name: 'Government', fee: 53666, duration: '4 years' },
    ],
    placements: { avgSalary: 75000, placementRate: 87, topRecruiters: ['Deloitte', 'Capital One', 'Google', 'EY', 'Booz Allen'] },
    majors: ['Business', 'Computer Science', 'Economics', 'Government', 'Biology'],
    tags: ['Public', 'Historic', 'Business', 'Liberal Arts'],
    imageUrl: '/colleges/uva.jpg',
  },
  {
    name: 'University of North Carolina at Chapel Hill',
    slug: 'unc',
    location: 'Chapel Hill, NC',
    state: 'North Carolina',
    type: 'SAFETY',
    description: 'Oldest public university in the US with strong all-around programs.',
    overview: 'UNC Chapel Hill is the nation\'s first public university, offering excellent academics at outstanding value. Known for its Kenan-Flagler Business School, journalism, and biomedical research, UNC combines academic rigor with a warm Southern campus culture.',
    fees: 36776,
    rating: 4.4,
    acceptanceRate: 17.0,
    avgAid: 18000,
    gpa: 3.75,
    sat: 1380,
    matchScore: 78,
    research: 87,
    campus: 90,
    social: 90,
    financial: 80,
    innovation: 78,
    diversity: 75,
    courses: [
      { name: 'Business', fee: 36776, duration: '4 years' },
      { name: 'Biology', fee: 36776, duration: '4 years' },
      { name: 'Computer Science', fee: 36776, duration: '4 years' },
      { name: 'Journalism', fee: 36776, duration: '4 years' },
    ],
    placements: { avgSalary: 68000, placementRate: 86, topRecruiters: ['Deloitte', 'Google', 'Wells Fargo', 'Duke Health', 'EY'] },
    majors: ['Business', 'Biology', 'Computer Science', 'Journalism', 'Pre-Med'],
    tags: ['Public', 'Historic', 'Value', 'Athletics'],
    imageUrl: '/colleges/unc.jpg',
  },
  {
    name: 'University of Wisconsin-Madison',
    slug: 'uw-madison',
    location: 'Madison, WI',
    state: 'Wisconsin',
    type: 'SAFETY',
    description: 'Major public research university with strong STEM and social sciences.',
    overview: 'UW-Madison is one of the largest and most productive research universities in the US. Located on the shores of Lake Mendota, it offers a vibrant campus experience with top programs in engineering, business, and life sciences.',
    fees: 39427,
    rating: 4.3,
    acceptanceRate: 49.0,
    avgAid: 14000,
    gpa: 3.65,
    sat: 1370,
    matchScore: 75,
    research: 90,
    campus: 88,
    social: 90,
    financial: 78,
    innovation: 82,
    diversity: 70,
    courses: [
      { name: 'Computer Science', fee: 39427, duration: '4 years' },
      { name: 'Engineering', fee: 39427, duration: '4 years' },
      { name: 'Business', fee: 39427, duration: '4 years' },
      { name: 'Biology', fee: 39427, duration: '4 years' },
    ],
    placements: { avgSalary: 68000, placementRate: 85, topRecruiters: ['Epic Systems', 'Google', 'Amazon', 'Microsoft', 'Deloitte'] },
    majors: ['Computer Science', 'Engineering', 'Business', 'Biology', 'Political Science'],
    tags: ['Public', 'Big Ten', 'Research', 'Value'],
    imageUrl: '/colleges/uwmadison.jpg',
  },
];

async function main() {
  console.log('🌱 Seeding database with', colleges.length, 'colleges...');

  for (const college of colleges) {
    await prisma.college.upsert({
      where: { slug: college.slug },
      update: college,
      create: college,
    });
    console.log('  ✓', college.name);
  }

  console.log('✅ Seed complete!');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
